remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme

title: Hwai-Ray Tung
description: ray [dot] tung [at] princeton.edu
logo: /static/linkedin_pic.jpg

sidebar:
  - name: CV
    link: /cv.html
  - name: Publications
    link: /research.html
  - name: Teaching
    link: /teaching.html

google_analytics: G-YY26VSQ1FG
