remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
title: Hwai-Ray Tung
description: ray [dot] tung [at] princeton.edu#<img src="/static/linkedin_pic.jpg" title="Hwai-Ray Tung">

sidebar:
  - name: CV
    #icon: <img src="/static/Adobe_32.png" title="pdf symbol">
    link: https://hwairaytung.github.io/cv.html
  - name: Publications
    link: https://hwairaytung.github.io/research.html
  - name: Teaching
    link: https://hwairaytung.github.io/teaching.html

# Google Analytics
google_analytics: G-YY26VSQ1FG
